spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:h2:mem:blog;
    driver-class-name: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true
      path: ${DB_CONSOLE_PATH}